language: cpp
sudo: required

compiler:
  - gcc
  
addons:
  apt:
    packages:
    - libglew-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then 
    ls;
    hg clone https://hg.libsdl.org/SDL SDL;
    cd SDL;
    mkdir build;
    cd build;
    ../configure;
    make;
    sudo make install;
    cd ~/Particle-Viewer;
   fi
    
  - if [ $TRAVIS_OS_NAME == osx ]; then 
  
    brew update && brew install sdl2 glew; 
    
    fi

script:
  - ls;
  - gcc ./src/main.cpp -o ./build/viewer  -lSDL2 -lGLEW -I. -g -O0 -Wall;
after_success:
  - echo "SUCCESS!!!"
after_failure:
  - echo "FAILURE"

branches:
  only:
    - master

notifications:
  email: true

os:
  - linux
  - osx
