language: cpp

sudo: required

os:
  - linux
  - osx
compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglew-dev
      - gcc-4.9
      - g++-4.9
      - clang
      - valgrind

before_install:
  - echo $LANG
  - echo $LC_ALL
  - #if [ $TRAVIS_OS_NAME == linux ]; then 
      sh ./scripts/linuxPre.sh;
    fi
    
  - if [ $TRAVIS_OS_NAME == osx ]; then 
  
    brew update && brew install sdl2 glew; 
    
    fi

script:
  - sh ./scripts/gccBuild.sh

after_success:
  - echo "SUCCESS!!!"

after_failure:
  - echo "FAILURE"

branches:
  whitelist:
    - master

notifications:
  email: true
  


