language: cpp

sudo: false

os:
  - linux
  - osx
compiler:
  - gcc-4.9
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglew-dev
      - gcc-4.9
      - g++-4.9
      - clang
      - valgrind
      - gdb
      - llvm-3.0-dev
      
cache:
  directories:
    - /home/travis/build/JPEGtheDev/SDL2_Build
    - /home/travis/build/JPEGtheDev/glm
    - /home/travis/build/JPEGtheDev/assimp
    - /home/travis/build/JPEGtheDev/cmake
    
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sh ./scripts/linuxPre.sh;
    fi
    
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      sh ./scripts/osxPre.sh;
    fi

script:
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      sh ./scripts/g++OSXBuild.sh;
    fi
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sh ./scripts/g++LinuxBuild.sh;
    fi
    
after_success:
  - echo "SUCCESS!!!"

after_failure:
  - echo "FAILURE"

branches:
  whitelist:
    - master

notifications:
  email: true



