language: cpp

sudo: false

os:
  - linux
  - osx
compiler:
  - gcc
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "flFt5aekg/6F5kn5i6j5dOeezwlbd8b56RgAReHYQH9zAtAIMqLlGx3F9khql4kLI7LP4X68mTrmIhOPtx0DRsFh249w3kgdrDSBYpM0WbMPRj9gDtHOUhhDZ3OPY46bNox6+7AIiPjBFxUxm1eibb9pwmZjRBUSzzCB/Lm7xTvsd7Ax7L/2Z+fFCa8JCslMCjUzmV5upS4fRCb64+XNmSRUaWXz+WP5a7bT9Dw8YjG25VQ7STqWbs9fYvw9n0bacKRfmvHxMpWXJo+v6VP0wRAXaDM+xSZYsMzVWv3gbkF+wXr37eClGHLdvwAzeXZtOD9d/UlCo3Sufm7fA3XGEqC+HqBvtnLvulUQnWvSfBZ5b6Ob/VUFqASixjyvwMnTBlyvCBC4qw2clk5DzIFrJvnyFcgOYfxS4V10MuKcgQSHf1i542beyE9M/sJbQ3Lp+qKM3CNaA/ueClViTuJ9WO8Hu8ORKwQWP7wrb+gX/hfyyQedaWf4pvnd5wWuzIoxahXwqgM3uO1M+ZPnTWKlMLXjKqJB6zRTSNOakzuH/I3h7UhD4YKLWNgo/RbVMaSZVTeYDBuFWqIiWBQQj7AnyMk+y6cJTX8QyO5g6XUFPwjqRclLzGvH1a3tc5p0g/bnOhpEKiLyDd4P56m3HqxmhYs+5YC38CukPJX/MAEHIAw="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglew-dev
      - gcc-4.9
      - g++-4.9
      - clang
      - valgrind
      - gdb
      - llvm-3.0-dev
  coverity_scan:
    project:
      name: "JPEGtheDev/Particle-Viewer"
      description: "<Your project description here>"
    notification_email: jpegthedev@gmail.com
    build_command_prepend: "mkdir build; cd build; cmake .."
    build_command:   "make"
    branch_pattern: scanner

cache:
  directories:
    - /home/travis/build/JPEGtheDev/SDL2_Build
    - /home/travis/build/JPEGtheDev/glm
    - /home/travis/build/JPEGtheDev/assimp
    - /home/travis/build/JPEGtheDev/cmake
					- /home/travis/build/JPEGtheDev/libRocket
    
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sh ./scripts/linuxPre.sh;
    fi
    
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      sh ./scripts/osxPre.sh;
    fi

script:
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      sh ./scripts/g++OSXBuild.sh;
    fi
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sh ./scripts/g++LinuxBuild.sh;
    fi
    
after_success:
  - echo "SUCCESS!!!"

after_failure:
  - echo "FAILURE"

branches:
  whitelist:
    - master

notifications:
  email: true



