language: cpp

sudo: false

os:
  - linux
  - osx
compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglew-dev
      - gcc-4.9
      - g++-4.9
      - clang
      - valgrind

cache:
  directories:
    - /home/travis/build/JPEGtheDev/SDL2_Build
    - /home/travis/build/JPEGtheDev/glm
    
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sh ./scripts/linuxPre.sh;
    fi
    
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      brew update && brew install sdl2 glew glm;
      sh ./scripts/osxPre.sh;
    fi

script:
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      sh ./scripts/g++OSXBuild.sh;
    fi
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sh ./scripts/g++LinuxBuild.sh;
    fi
    
after_success:
  - echo "SUCCESS!!!"

after_failure:
  - echo "FAILURE"

branches:
  whitelist:
    - master

notifications:
  email: true
  


