language: cpp
sudo: false

compiler:
  - gcc
  
addons:
  apt:
    packages:
    - libglew-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then 
    hg clone https://hg.libsdl.org/SDL SDL;
    cd SDL;
    mkdir build;
    cd build;
    ../configure;
    make;
    ls -all;
    #make install;
   fi
    
  - if [ $TRAVIS_OS_NAME == osx ]; then 
  
    brew update && brew install sdl2 glew; 
    
    fi

script: echo "Build Complete"
after_success:
  - echo "SUCCESS!!!"
after_failure:
  - echo "FAILURE"

branches:
  only:
    - master

notifications:
  email: true

os:
  - linux
  - osx
