language: cpp

sudo: false

os:
  - linux
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc
      - g++
      - clang
      - cmake
      #- valgrind
      #- gdb
      - xorg-dev 
      - libglu1-mesa-dev
      - libfreetype6-dev

before_install:
  - echo $LANG
  - echo $LC_ALL

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sh ./scripts/linuxBuild.sh;
    fi

after_success:
  - echo "SUCCESS!!!"

after_failure:
  - echo "FAILURE"

branches:
  whitelist:
    - master

notifications:
  email: true



